import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import StyledComponentsRegistry from "@/lib/registry";
import ThemeProvider from "@/lib/ThemeProvider";
import GlobalStyle from "@/styles/GlobalStyle";

import Header from "@/components/header";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable}`}>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <GlobalStyle />
            <Header />
            {children}
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
